from api.tests.ajax import *
from api.tests.function_detail import *
from api.tests.function_list import *
from api.tests.mathematical_object_detail import *
from api.tests.mathematical_object_list import *
from api.tests.mathematical_object_function_detail import *
from api.tests.mathematical_object_function_list import *
from api.tests.mathematical_object_name_detail import *
from api.tests.mathematical_object_name_list import *
from api.tests.mathematical_object_related_detail import *
from api.tests.mathematical_object_related_list import *
from api.tests.mathematical_object_tag_detail import *
from api.tests.mathematical_object_tag_list import *
from api.tests.models import *
from api.tests.name_detail import *
from api.tests.name_list import *
from api.tests.tag_detail import *
from api.tests.tag_list import *
