language: python

python:
  - "3.6"

services:
  - postgresql

before_install:
  - cd oems

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database oems_db;' -U postgres

script:
  - python manage.py test
  - coverage run --source=api,front manage.py test

after_success:
  - coveralls
