

TYPE_CHOICES = (
    ('S', "SERIES"),
    ('P', "PRODUCT"),
)

MATHEMATICAL_OBJECT_REPRESENTATION_MAX_LENGTH = 65535
MATHEMATICAL_OBJECT_CONVERGENCE_RADIUS_MAX_LENGTH = 255

FUNCTION_REPRESENTATION_MAX_LENGTH = 255

NAME_REPRESENTATION_MAX_LENGTH = 255

PROPOSITION_REPRESENTATION_MAX_LENGTH = 65535

TAG_REPRESENTATION_MAX_LENGTH = 255
